### ISSUE TITLE
Error deserializing repeated fields

### ISSUE THREAD

**Issue by Sanceilaks** [rakaly/hoi4save#3]
When attempting to deserialize a section of code that contains repeated `saved_event_target` fields in the given format, the deserialization fails with the error `Hoi4Error(Deserialize(Error(Deserialize(DeserializeError { kind: Unsupported("not an object") })))).`

#### Steps to Reproduce
1. Attempt to deserialize code containing repeated `saved_event_target` fields.
```
saved_event_target={
	country="CHI"
	name="WTT_current_china_leader"
}
saved_event_target={
	country="PRC"
	name="WTT_communist_china"
}
saved_event_target={
	country="YUG"
	name="yugoslavia_wedding_partner"
}
saved_event_target={
	state=800
	name="TUR_kurdish_state_event_target"
}
```
2. Run the deserialization:
```rust
#[derive(Deserialize, Serialize, Debug, Clone)]
pub struct SavedEventTarget {
    pub country: Option<String>,
    pub state: Option<i32>,
    pub name: String,
}

// in struct
saved_event_target: Vec<SavedEventTarget>
```

**Comment by nickbabcock** [comment]
This seems like a problem that can be solved with the [`duplicated` attribute](https://docs.rs/jomini/0.21.3/jomini/#quick-start)

**Comment by Sanceilaks** [comment]
Thanks!
